while True:
	x = int(input("Please enter first number: "))
	y = int(input("Please enter second number: "))
	print("\n ----E_wooder(Eymen ERDOĞDU)was-here---- \n")
	print(x,"+",y,"=",x+y)
	print(x,"-",y,"=",x-y)
	print(x,"*",y,"=",x*y)
	print(x,"/",y,"=",x/y)
	print(x," mod ",y,"=",x%y)
	print("\n ----E_wooder(Eymen ERDOĞDU)was-here---- \n")
